### PR TITLE
feat(if intrinsics): generalized solution to support more types

### PR DESCRIPTION
**Pull request by xrn**
*Issue #, if available:*

https://github.com/awslabs/goformation/issues/471

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by xrn** [comment]
@rubenfonseca any chance that you will take a look on this? (Previous implementation of If with 

```
switch v := ifEqual.(type) {
```

was written by my team member as well and merged to master but seems that it can be simplified

**Review by rubenfonseca — CHANGES_REQUESTED** [review]
Hi @xrn thanks for looking into this! Is it possible to write a test case that covers this behaviour, and that would fail before your change? Maybe you can re-use the code from the original issue. Thank you!

**Comment by xrn** [comment]
@rubenfonseca - unfortunately it won't be simple. I have my own for of this repo where for some resources where I need to use parameter and then Intrinsics functions. I have to change 

```
&apigateway.RestApi{
		Name: "test",
		Description: "test",
		EndpointConfiguration: cloudformation.If("PrivateApiGateway",
			apigateway.RestApi_EndpointConfiguration{
				Types: cloudformation.Strings("PRIVATE"),
				VpcEndpointIds: cloudformation.Strings(
					cloudformation.Ref("ExecuteApiEndpointId"),
				),
			},
```
apigateway.RestApi.EndpointConfiguration from apigateway.RestApi_EndpointConfiguration to string/interface{} to be able to accept this if. But still current if implementation is incorrect with current version I will get 

```
 ApiGateway:
    Properties:
      Name: "test"
      Description: "test"
      EndpointConfiguration: eyAiRm46OklmIiA6IFsgIlByaXZhdGVBcGlHYXRld2F5IiwgeyUhcSgqW11zdHJpbmc9JltQUklWQVRFXSkgJSFxKCpbXXN0cmluZz0mW2V5QWlVbVZtSWpvZ0lrVjRaV04xZEdWQmNHbEZibVJ3YjJsdWRFbGtJaUI5XSkgIiIgIiIgW10gbWFwW10gIiJ9LCB7JSFxKCpbXXN0cmluZz0mW0VER0VdKSAlIXEoKltdc3RyaW5nPTxuaWw+KSAiIiAiIiBbXSBtYXBbXSAiIn0gXSB9
```

After fix

```
ApiGateway:
    Properties:
      Name: "test"
      Description: "test"
      EndpointConfiguration:
        Fn::If:
        - PrivateApiGateway
        - Types:
          - PRIVATE
          VpcEndpointIds:
          - Ref: ExecuteApiEndpointId
        - Types:
          - EDGE
```

**Comment by xrn** [comment]
Hi @rubenfonseca - any chance that you will take a look on this?

**Review by rubenfonseca — APPROVED** [review]

**Comment by rubenfonseca** [comment]
Thanks @xrn, merging it

**Pull request merged**
