### PR TITLE
Adding tests for new Go struct generator

### PR DESCRIPTION
**Pull request by PaulMaddox**
Added a basic test for marhsalling/unmarshalling a template

### CODE REVIEW

**Comment by sanathkr** [comment]
Does the JSON schema assume values can be intrunsics as well? I.e. A string properly can be represented by an intrinsic function dict

**Comment by PaulMaddox** [comment]
@sanathkr  - No. That will require some additional thought on how best to implement.

**Comment by PaulMaddox** [comment]
For validating a template with intrinsics against a JSON Schema, I believe we could define each of the properties as either a type (primitive or custom type etc), OR an "intrinsic" type, using the ['anyOf' keyword in the JSON Schema specification](https://github.com/json-schema/json-schema/wiki/anyOf,-allOf,-oneOf,-not). We can then define types for each intrinsic function.

I'll play around with this and submit a separate PR. For now, I recommend merging this one.

**Comment by sanathkr** [comment]
(or) as in your proposal, pre-process the template to reduce intrinsics to primitive types. So validator will succeed.

**Pull request merged**
