### PR TITLE
[Fix] Select the correct polymorphic type

### PR DESCRIPTION
**Pull request by grahamjenson**
*Issue*

Polymorphic types are currently selected by first match. Sometimes polymorphic types have multiple matches and the first and returned match is incorrect.

*Description of changes:*

This fix selects the polymorphic type based on the heuristic of the most amount of data calculated by marshaling to JSON and counting characters. This is not perfect but it fixes the bug

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by PaulMaddox** [comment]
I like this - but can you add a couple of tests for it?

**Comment by grahamjenson** [comment]
Good idea, will get some tests out soon :)

**Comment by grahamjenson** [comment]
@PaulMaddox Added two tests that highlight the bug this PR fixes and hopefully will stop a regression.

**Pull request merged**
