### PR TITLE
Fix resource generation

### PR DESCRIPTION
**Pull request by PaulMaddox**
*Issue #, if available:* n/a

*Description of changes:*
Works around a bug in the AWS CloudFormation specification that mistakenly lists a field with a `PrimitiveType: Map`.  

Unfortunately due to another change (i need to track down which) - lots of tests are failing. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by PaulMaddox** [comment]
@grahamjenson - it looks like the change to make resources use pointers (https://github.com/awslabs/goformation/commit/5665ed1de270928edb8d0900fc2d9a23c173b3f2) is causing lots of tests to fail. I guess this was previously masked by the above CloudFormation specification bug.

**Comment by PaulMaddox** [comment]
I have a gut feeling this is because in each resource there is a `MarshalJSON()` method (e.g. https://github.com/awslabs/goformation/blob/master/cloudformation/aws-apigateway-deployment.go#L85). The main purpose of this marshaller hook is to wrap the goformation object fields in a "Properties" field (similar to what CFN does).

Your change above refactors this to be a method on a pointer method receiver, and from memory, the JSON marshaller only runs the method if it's a straight method receiver.  

As such, JSONMarshal() never gets called, so when goformation's objects are converted to JSON, all of the property fields just sit at the root, not under a "Properties" field.

I think. I need to do some more testing and confirm.

Can you just re-iterate the value of refactoring resources to be pointers? I'm sure you had a good reason, I just want to be able to reason about whether we keep it or revert.

Once this is done and goformation is updating from the cfn spec again, i can start reviewing your other PRs.

**Comment by grahamjenson** [comment]
In #155 change the returned value to pointers so that a resources properties could be changes, e.g. 

```
template, _ := goformation.Open("template.yaml")
function, _ := template.GetAWSServerlessFunctionWithName("FunctionName")
function.FunctionName = "edit-the-name"
template.YAML()
```

A solution to these failed tests might be in another submitted PR, will have a look into this.

**Comment by grahamjenson** [comment]
Hey @PaulMaddox 

If you apply this diff and then rerun `go generate` I was able to get all tests passing. Once you have merged this awesome PR, ping me and I will make sure to update all my other PRs to make sure that there are no conflicts. Cheers!

```diff
diff --git a/generate/templates/resource.template b/generate/templates/resource.template
index 54943b6..5fab624 100644
--- a/generate/templates/resource.template
+++ b/generate/templates/resource.template
@@ -81,7 +81,7 @@ func (r *{{.StructName}}) SetCreationPolicy(policy *CreationPolicy) {
 {{if not .IsCustomProperty}}
 // MarshalJSON is a custom JSON marshalling hook that embeds this object into
 // an AWS CloudFormation JSON resource's 'Properties' field and adds a 'Type'.
-func (r *{{.StructName}}) MarshalJSON() ([]byte, error) {
+func (r {{.StructName}}) MarshalJSON() ([]byte, error) {
        type Properties {{.StructName}}
        return json.Marshal(&struct{
                Type string
@@ -93,7 +93,7 @@ func (r *{{.StructName}}) MarshalJSON() ([]byte, error) {
                {{if .HasCreationPolicy}}CreationPolicy *CreationPolicy `json:"CreationPolicy,omitempty"`{{end}}
        }{
                Type: r.AWSCloudFormationType(),
-               Properties: (Properties)(*r),
+               Properties: (Properties)(r),
                DependsOn: r._dependsOn,
                Metadata: r._metadata,
                DeletionPolicy: r._deletionPolicy,
@@ -140,6 +140,8 @@ func (t *Template) GetAll{{.StructName}}Resources () map[string]*{{.StructName}}
     results := map[string]*{{.StructName}}{}
        for name, untyped := range t.Resources {
                switch resource := untyped.(type) {
+               case {{.StructName}}:
+                       results[name] = &resource
                case *{{.StructName}}:
                        // We found a strongly typed resource of the correct type; use it
                        results[name] = resource
@@ -168,6 +170,8 @@ func (t *Template) GetAll{{.StructName}}Resources () map[string]*{{.StructName}}
 func (t *Template) Get{{.StructName}}WithName (name string) (*{{.StructName}}, error) {
        if untyped, ok := t.Resources[name]; ok {
                switch resource := untyped.(type) {
+               case {{.StructName}}:
+                       return &resource, nil
                case *{{.StructName}}:
                        // We found a strongly typed resource of the correct type; use it
                        return resource, nil
diff --git a/goformation_test.go b/goformation_test.go
index fc1c304..dc860b3 100644
--- a/goformation_test.go
+++ b/goformation_test.go
@@ -310,7 +310,7 @@ var _ = Describe("Goformation", func() {
                function, err := template.GetAWSLambdaFunctionWithName("MyLambdaFunction")
                It("should be able to retrieve a specific Lambda function with GetAWSLambdaFunctionWithName(template, name)", func() {
                        Expect(err).To(BeNil())
-                       Expect(function).To(BeAssignableToTypeOf(cloudformation.AWSLambdaFunction{}))
+                       Expect(function).To(BeAssignableToTypeOf(&cloudformation.AWSLambdaFunction{}))
                })
 
                It("should have the correct Handler property", func() {
```

**Comment by PaulMaddox** [comment]
@grahamjenson - thanks. All merged.

**Pull request merged**
